cloud:
  aws:
    credentials:
      access-key: AKIASSDXKHYNMWED65WZ
      secret-key: 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
    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: collector-image-bucket
spring:
  application:
    name: ImageService
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB
  cloud:
    function:
      definition: email
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      input-bindings:
#        destination
      output-bindings:

server:
  port: 9090





# Kafka
#  spring.cloud.stream.kafka.binder.brokers=localhost:9092
#  spring.cloud.function.definition=email
#  spring.cloud.stream.bindings.email-in-0.destination=send-OrderPlacedEvent
#  spring.cloud.stream.bindings.email-out-0.destination=receive-OrderPlacedEvent
#  spring.cloud.stream.bindings.email-in-0.group=email-group


